---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r include=FALSE}
library(flexdashboard)
library(knitr)
library(rmarkdown)
library(tidyverse)
library(plotly)
library(haven)
#we should delete unnecessary packages 
```

```{r nhats}

nhats = read_sas("./final_data/nhats_r5.sas7bdat")  %>%
  select(spid, hc5depresan1, hc5depresan2, r5dgender, r5d2intvrage, rl5dracehisp, md5canewlker, 
         sn5dnumsn, cg5ratememry, hc5health, wb5truestme4) %>%
  janitor::clean_names() %>%   
  filter(hc5depresan1 > 0, hc5depresan2 > 0, sn5dnumsn >= 0, r5d2intvrage > 0, md5canewlker > 0, 
         cg5ratememry > 0, hc5health > 0, wb5truestme4 > 0, rl5dracehisp < 5)

nhats %>% 
  select(hc5depresan1, hc5depresan2)  %>% 
  rowSums(na.rm = TRUE) -> nhats$phq.total

nhats = nhats %>%
  mutate(phq.total = phq.total - 2) %>% 
  mutate(phq_cat = if_else(phq.total < 3, "Low Depression Risk", "Elevated Depression Risk")) %>% 
  mutate(
    gender = recode(r5dgender, `1` = "Male", `2` = "Female"),
    gender = factor(gender),
    age_cat = recode(r5d2intvrage, `1` = "65 to 69", `2` = "70 to 74", `3` = "75 to 79", 
                 `4` = "80 to 84", `5` = "85 to 89", `6` = "90+"),
    age_cat = factor(age_cat, levels = c("65 to 69", "70 to 74", "75 to 79", "80 to 84", 
                  "85 to 89", "90+"), ordered = TRUE),
    race_ethnicity = recode(rl5dracehisp, `1` = "White, non-hispanic", `2` = "Black, non-hispanic", 
                  `3` = "Other, non-hispanic", `4` = "Hispanic"),
    race_ethnicity = factor(race_ethnicity),
    cane_walker_wheelchair = recode(md5canewlker, `1` = "Yes", `2` = "No"),
    cane_walker_wheelchair = factor(cane_walker_wheelchair),
    memory = recode(cg5ratememry, `1` = "Excellent", `2` = "Very Good", `3` = "Good", 
                    `4` = "Fair", `5` = "Poor"),
    memory = factor(memory, c("Excellent", "Very Good", "Good", "Fair", "Poor"), 
                    ordered = TRUE),
    overall_health = recode(hc5health, `1` = "Excellent", `2` = "Very Good", `3` = "Good", 
                    `4` = "Fair", `5` = "Poor"),
    overall_health = factor(overall_health, levels = c("Excellent", "Very Good", "Good", "Fair", 
                    "Poor"), ordered = TRUE),
    likes_living_situation = recode(wb5truestme4, `1` = "Agree a lot", `2` = "Agree a little", 
                    `3` = "Agree not at all"),
    likes_living_situation = factor(likes_living_situation, c("Agree a lot", "Agree a little", 
                    "Agree not at all"), ordered = TRUE)
)

```

Column {data-width=500}
-----------------------------------------------------------------------

### Figure 1: Participant view of living situation predictor against PHQ-2, stratified by race (EM) to show the differences in PHQ-2 (depression risk scale) distribution across categories. 

```{r}

living_plot = nhats %>% 
  ggplot(aes(x = likes_living_situation, y = phq.total, color = race_ethnicity)) + 
  geom_point(position = "jitter", size = 0.5) + 
  labs(title = "View of living situation and PHQ-2 score distribution",
       x = "Likes living situation", y = "PHQ-2 score") + 
  facet_grid(rows = vars(race_ethnicity)) + 
  theme(legend.position = "none")

ggplotly(living_plot)

```

###  Figure 2: Differences in depression outcome by social network (stratified by gender) and perceived overall health:

```{r}
sn_plot = nhats %>% group_by(phq_cat, age_cat, gender) %>% 
  summarise(
    mean = mean(social_network_size)
  ) %>%
  mutate(age_cat = factor(age_cat)) 
         
sn_plot %>%
  ggplot(aes(x = age_cat, y = mean, group = gender, color = gender)) + 
  geom_line(alpha = 0.5) + facet_grid(~phq_cat) + geom_point() +
  theme(axis.text.x = element_text(angle = 30, vjust = 0.7)) +
  theme(panel.background = element_rect(fill = "white", colour = "grey50")) +
  labs(y = "Mean Social Network Size", x = "Age Groups") + scale_color_viridis_d(name = "Gender")


nhats %>% 
  filter(hc5health > 0) %>%
  ggplot(aes(x = overall_health, group = phq_cat)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat = "count") +
    geom_text(aes( label = scales::percent(round(..prop.., 2)),
                   y = ..prop.. ), stat = "count", vjust = -0.5, size = 3) +
    labs(y = "Proportion of Respondents", x = "Perceived Overall Health", fill = "Overall Health") +
    theme(legend.position = "none")  + theme(axis.text.x = element_text(angle = 30, vjust = 0.7)) +
    facet_grid(~phq_cat) + scale_y_continuous(labels = scales::percent) + 
    theme(panel.background = element_rect(fill = "white", colour = "grey50")) +
    scale_fill_viridis_d()

```

Column {data-width=500}
-----------------------------------------------------------------------

### Figure 3: Differences in depression outcome by self-rated memory. 

```{r}

mem_plot = nhats %>%  group_by(phq_cat, memory) %>% 
  summarise(n = n()) %>% mutate(
  proportion = (n / sum(n)))

  memory_plot = mem_plot %>% mutate(memory = factor(memory)) %>% drop_na() %>%   
    ggplot(aes(x = memory, y = proportion, group= phq_cat)) + geom_line(alpha = 0.4) +
  
    geom_point(alpha = 0.5, color = "red") + 
    facet_grid(~phq_cat) + 
    labs( title = "Self rated memory and depression outcomes",
    x = "Self Rated Memory", y = " Proportion of Respondents")+  
    scale_y_continuous(labels = scales::percent)
  
ggplotly(memory_plot)

```

### Figure 4: Differences in depression outcome by use of cane, walker/wheelchair. 

```{r}

cane_walker_wc_plot = nhats %>%  
    group_by(phq_cat, cane_walker_wheelchair) %>% 
    summarise(n = n()) %>%  
    mutate(proportion = (n / sum(n)))

cane_walker_wc_plot = 
  cane_walker_wc_plot %>%  
  ggplot(aes(x = cane_walker_wheelchair, y =proportion)) + 
  geom_col(fill= "light blue") + facet_grid(~phq_cat)+
  labs( title = "Use of cane walker/wheelchair and depression outcomes",
      x = "Asked if used a cane, walker/ wheel chair", y = " Proportion of respondents")+  
    scale_x_discrete(
      labels = c("Yes","No")) + 
    scale_y_continuous(labels = scales::percent)

  ggplotly(cane_walker_wc_plot)
  
```
